apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-1
  labels:
    app: app-1
  namespace: namespace-1
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - external:
      metricName: custom.googleapis.com|exporter
      metricSelector:
        matchLabels:
          resource.labels.project_id: red-forklift-301112
          resource.labels.location: us-central1-c
          resource.labels.namespace: namespace-1
          resource.labels.node_id: app-1
      targetAverageValue: 100
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-1

