apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: exporter
  labels:
    app: exporter
  namespace: namespace-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exporter
  namespace: namespace-1
subjects:
- kind: ServiceAccount
  name: exporter
  namespace: namespace-1
