apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: exporter
  labels:
    app: exporter
  namespace: namespace-1
rules:
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]
