apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: exporter
  labels:
    app: exporter
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch"]
